(function(){"use strict";const u=t=>document.querySelector(t),F=u("#bank");if(!F)return;const T=F.dataset.tool,v=t=>String(t==null?"":t).replace(/[&<>"]/g,e=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[e]),p=t=>(t<0?"\u2212":"")+"$"+Math.abs(Math.round(t*100)/100).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});let c=[];const A=t=>{const e=u("#bank-status");e&&(e.textContent=t)};function M(t){t=String(t||"").trim();let e;if(e=t.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/))return new Date(+e[1],+e[2]-1,+e[3]);if(e=t.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{2,4})/)){let s=+e[3];return s<100&&(s+=2e3),new Date(s,+e[1]-1,+e[2])}if(e=t.match(/^(\d{1,2})\/(\d{1,2})$/))return new Date(new Date().getFullYear(),+e[1]-1,+e[2]);const n=new Date(t);return isNaN(n)?null:n}const y=t=>t==null?NaN:(t=String(t).replace(/[$,\s]/g,""),/^\(.*\)$/.test(t)&&(t="-"+t.slice(1,-1)),/CR$/i.test(t)&&(t=t.replace(/CR$/i,"")),/DR$/i.test(t)&&(t="-"+t.replace(/DR$/i,"")),parseFloat(t));function G(t){const e=[];let n=[],s="",o=!1;for(let a=0;a<t.length;a++){const i=t[a];o?i==='"'&&t[a+1]==='"'?(s+='"',a++):i==='"'?o=!1:s+=i:i==='"'?o=!0:i===","?(n.push(s),s=""):i===`
`||i==="\r"?(i==="\r"&&t[a+1]===`
`&&a++,n.push(s),e.push(n),n=[],s=""):s+=i}return(s||n.length)&&(n.push(s),e.push(n)),e.filter(a=>a.some(i=>i.trim()))}function L(t){const e=G(t);if(!e.length)return[];const n=e[0].map(r=>r.toLowerCase().trim()),s=(...r)=>n.findIndex(d=>r.some(g=>d===g||d.includes(g))),o=s("date","posted"),a=s("description","memo","payee","details","narrative","transaction"),i=s("amount"),m=s("debit","withdrawal","money out"),l=s("credit","deposit","money in"),h=o>=0,b=[];for(const r of e.slice(h?1:0)){let d,g,f;h?(d=M(r[o]),g=r[a>=0?a:1]||"",f=i>=0?y(r[i]):(y(r[l])||0)-(y(r[m])||0),i>=0&&isNaN(f)&&(f=(y(r[l])||0)-(y(r[m])||0))):(d=M(r[0]),f=[...r.map(y)].reverse().find(O=>!isNaN(O)),g=r.slice(1).filter(O=>isNaN(y(O))).join(" ")),d&&!isNaN(f)&&f!==0&&b.push({date:d,desc:g.trim(),amount:f})}return b}function R(t){const e=[],n=/^(\d{1,2}[\/.-]\d{1,2}(?:[\/.-]\d{2,4})?|\d{4}-\d{2}-\d{2}|[A-Z][a-z]{2} \d{1,2},? \d{4}|[A-Z][a-z]{2} \d{1,2})\s+(.*?)\s+(-?\(?\$?[\d,]+\.\d{2}\)?(?:\s?(?:CR|DR))?)(?:\s+(-?\(?\$?[\d,]+\.\d{2}\)?))?\s*$/;for(const s of t.split(/\n/)){const a=s.replace(/\s+/g," ").trim().match(n);if(!a)continue;const i=M(a[1]),m=y(a[3]);if(!i||isNaN(m))continue;let l=m;const h=a[2];l>0&&/\b(withdrawal|debit|purchase|payment to|pos|ach debit|check #?\d|fee|atm)\b/i.test(h)&&!/deposit|refund|credit/i.test(h)&&(l=-l),e.push({date:i,desc:h,amount:l})}return e}async function V(t){if(!window.pdfjsLib)throw new Error("PDF reader not loaded");pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";const e=await pdfjsLib.getDocument({data:await t.arrayBuffer()}).promise;let n="";for(let s=1;s<=e.numPages;s++){const a=await(await e.getPage(s)).getTextContent(),i={};for(const l of a.items){const h=Math.round(l.transform[5]);(i[h]=i[h]||[]).push({x:l.transform[4],s:l.str})}const m=Object.keys(i).map(Number).sort((l,h)=>h-l);for(const l of m)n+=i[l].sort((h,b)=>h.x-b.x).map(h=>h.s).join(" ")+`
`}return R(n)}async function D(t,e){let n=[];A("Reading\u2026");for(const o of t||[])try{const a=o.name.toLowerCase();if(a.endsWith(".pdf"))n=n.concat(await V(o));else{const i=await o.text();n=n.concat(a.endsWith(".csv")||i.includes(",")?L(i):R(i))}}catch(a){A("Could not read "+o.name+": "+a.message)}e&&e.trim()&&(n=n.concat(e.includes(",")&&/date/i.test(e.split(`
`)[0])||L(e).length>2?L(e):R(e)));const s=new Set;c=n.filter(o=>{const a=I(o.date)+"|"+o.desc+"|"+o.amount;return s.has(a)?!1:(s.add(a),!0)}).sort((o,a)=>o.date-a.date),A(c.length?`${c.length} transactions from ${C().length} months (${w(c[0].date)} \u2013 ${w(c[c.length-1].date)}).`:"No transactions recognised \u2014 try the CSV export from your bank instead of a PDF."),k()}const $=t=>t.getFullYear()+"-"+String(t.getMonth()+1).padStart(2,"0"),I=t=>$(t)+"-"+String(t.getDate()).padStart(2,"0"),w=t=>t.toLocaleDateString("en-US",{month:"short",year:"numeric"}),C=()=>[...new Set(c.map(t=>$(t.date)))].sort(),U=t=>t.toLowerCase().replace(/\b(\d{2,}|[a-z]*\d+[a-z0-9]*)\b/g,"").replace(/\b(ppd|ccd|web|id|des|co|inc|llc|payroll|dir dep|direct dep|deposit|ach|credit|debit|pos|purchase|card|recurring|payment|online|transfer|the)\b/g,"").replace(/[^a-z ]/g," ").replace(/\s+/g," ").trim().split(" ").slice(0,3).join(" ")||"other",X=t=>/\b(savings|checking|internal|between accounts|own account|online banking transfer|mobile transfer|transfer to|xfer to|from self|to self|loan (proceeds|disbursement)|refund|reversal)\b/i.test(t)||/\b(zelle|venmo|cash app|paypal)\b/i.test(t)&&/\b(self|own|savings|checking)\b/i.test(t);function Y(t){const e=c.filter(r=>r.amount>0&&(t.includeTransfers?!0:!X(r.desc))),n={},s={};for(const r of e){n[$(r.date)]=(n[$(r.date)]||0)+r.amount;const d=U(r.desc);s[d]=s[d]||{total:0,n:0,months:new Set},s[d].total+=r.amount,s[d].n++,s[d].months.add($(r.date))}const o=C(),a=e.reduce((r,d)=>r+d.amount,0),i=Math.max(1,o.length),m=t.business?1-(+t.expense||50)/100:1,l=a/i*m,h=e.filter(r=>r.amount>3*(a/Math.max(1,e.length))&&r.amount>5e3),b=Object.entries(s).sort((r,d)=>d[1].total-r[1].total).slice(0,12).map(([r,d])=>({p:r,total:d.total,n:d.n,months:d.months.size,recurring:d.months.size>=Math.min(3,i)&&d.n>=Math.min(3,i)}));return{dep:e,byMonth:n,ms:o,total:a,n:i,avg:l,ratio:m,large:h,payers:b,recurringIncome:b.filter(r=>r.recurring).reduce((r,d)=>r+d.total,0)/i*m}}function _(t){const e=Y(t);return c.length?`<div class="stub"><div class="stub-head"><div><div class="stub-co">Bank-statement income analysis</div><div class="stub-addr">${e.ms.length} month${e.ms.length>1?"s":""} \xB7 ${w(c[0].date)} \u2013 ${w(c[c.length-1].date)} \xB7 ${e.dep.length} deposits${t.includeTransfers?" (transfers included)":" (transfers excluded)"}</div></div><div class="stub-meta"><div><b>Qualifying monthly income</b></div><div class="big">${p(e.avg)}</div><div class="muted small">${t.business?"business statements, "+(100-(+t.expense||50))+"% of deposits":"personal statements, 100% of deposits"}</div></div></div>
<table class="stub-t"><thead><tr><th>Month</th><th class="n">Eligible deposits</th></tr></thead><tbody>${e.ms.map(n=>`<tr><td>${n}</td><td class="n">${p(e.byMonth[n]||0)}</td></tr>`).join("")}<tr class="tot"><td>Total \xF7 ${e.n} months</td><td class="n">${p(e.total/e.n)}</td></tr></tbody></table>
<table class="stub-t"><thead><tr><th>Source of deposits</th><th class="n">Deposits</th><th class="n">Months</th><th class="n">Total</th><th class="n">Per month</th></tr></thead><tbody>${e.payers.map(n=>`<tr><td>${v(n.p)}${n.recurring?' <span class="muted small">recurring</span>':""}</td><td class="n">${n.n}</td><td class="n">${n.months}</td><td class="n">${p(n.total)}</td><td class="n">${p(n.total/e.n)}</td></tr>`).join("")}</tbody></table>
<p><b>Recurring income only:</b> ${p(e.recurringIncome)} a month from sources that deposit in ${Math.min(3,e.n)}+ months \u2014 the figure a cautious underwriter starts from.${e.large.length?` <b>${e.large.length} large one-off deposit${e.large.length>1?"s":""}</b> (${e.large.map(n=>p(n.amount)).join(", ")}) will need a source letter.`:""}</p>
<p class="stub-foot">Method: eligible deposits (transfers between own accounts excluded unless included above) summed over the months covered and divided by the number of months; business accounts reduced by the expense ratio. Lenders apply their own rules \u2014 this shows where you stand before you apply. Computed in your browser; nothing was uploaded.</p></div>`:'<p class="muted">Add statements to see the calculation.</p>'}function q(t,e){const n=Y(t);return c.length?`<div class="stub${e?"":" wm"}"><div class="stub-head"><div><div class="stub-co">${v(t.name)||"Applicant name"}</div><div class="stub-addr">Statement of income from bank deposits</div></div><div class="stub-meta"><div>${new Date().toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"})}</div><div>Period: ${w(c[0].date)} \u2013 ${w(c[c.length-1].date)}</div></div></div>
<p>The following summarises deposits to the account(s) whose statements accompany this document (${v(t.bank)||"bank"}, account ending ${v(t.acct4)||"____"}). Transfers between the applicant's own accounts are excluded.</p>
<table class="stub-t"><thead><tr><th>Month</th><th class="n">Deposits</th></tr></thead><tbody>${n.ms.map(s=>`<tr><td>${s}</td><td class="n">${p(n.byMonth[s]||0)}</td></tr>`).join("")}<tr class="tot"><td>Average per month (${n.n} months)</td><td class="n">${p(n.total/n.n)}</td></tr></tbody></table>
<table class="stub-t"><thead><tr><th>Source</th><th class="n">Months present</th><th class="n">Average per month</th></tr></thead><tbody>${n.payers.slice(0,8).map(s=>`<tr><td>${v(s.p)}</td><td class="n">${s.months} of ${n.n}</td><td class="n">${p(s.total/n.n)}</td></tr>`).join("")}</tbody></table>
<p class="stub-foot">Prepared by the applicant with paysums.com from the bank statements listed; every figure is the sum of deposits shown on those statements, which should be provided alongside this summary. Not a bank document and not verified by paysums. Document ID PS-${Math.abs(Math.round(n.total*7919+n.n)).toString(16).toUpperCase()}.</p>${e?"":'<div class="stub-mark">PREVIEW</div>'}</div>`:""}function B(){if(!c.length)return'<p class="muted">Add statements to find recurring charges.</p>';const t=c.filter(o=>o.amount<0),e={};for(const o of t){const a=U(o.desc);(e[a]=e[a]||[]).push(o)}const n=[];for(const[o,a]of Object.entries(e)){if(a.length<2)continue;a.sort((f,N)=>f.date-N.date);const i=[];for(let f=1;f<a.length;f++)i.push((a[f].date-a[f-1].date)/864e5);const m=i.sort((f,N)=>f-N)[Math.floor(i.length/2)],l=a.map(f=>-f.amount),h=Math.max(...l)-Math.min(...l)<=Math.max(2,.15*Math.max(...l)),b=m>=25&&m<=35?"monthly":m>=6&&m<=8?"weekly":m>=12&&m<=16?"biweekly":m>=85&&m<=95?"quarterly":m>=350&&m<=380?"yearly":null;if(!b||!h)continue;const r=l[l.length-1],d=r*{monthly:12,weekly:52,biweekly:26,quarterly:4,yearly:1}[b],g=l[0];n.push({p:o,cadence:b,per:r,yearly:d,n:a.length,rise:r>g*1.02?g:0,last:a[a.length-1].date})}n.sort((o,a)=>a.yearly-o.yearly);const s=n.reduce((o,a)=>o+a.yearly,0);return`<div class="stub"><div class="stub-head"><div><div class="stub-co">Recurring charges found</div><div class="stub-addr">${n.length} recurring payees across ${C().length} months</div></div><div class="stub-meta"><div><b>Per year</b></div><div class="big">${p(s)}</div><div class="muted small">${p(s/12)} a month</div></div></div>
<table class="stub-t"><thead><tr><th>Payee</th><th>Cadence</th><th class="n">Amount</th><th class="n">Per year</th><th>Note</th></tr></thead><tbody>${n.map(o=>`<tr><td>${v(o.p)}</td><td>${o.cadence}</td><td class="n">${p(o.per)}</td><td class="n">${p(o.yearly)}</td><td>${o.rise?"price rose from "+p(o.rise):""}${o.cadence==="yearly"?"renews "+o.last.toLocaleDateString("en-US",{month:"short",day:"numeric"}):""}</td></tr>`).join("")||'<tr><td colspan="5">No regular charges detected \u2014 add more months.</td></tr>'}</tbody></table>
<p class="stub-foot">A charge counts as recurring when the same payee is billed at a steady interval for a near-identical amount. Computed in your browser; nothing was uploaded.</p></div>`}function W(){if(!c.length)return'<p class="muted">Add a statement to convert it.</p>';const t=c.slice(0,15).map(e=>`<tr><td>${I(e.date)}</td><td>${v(e.desc)}</td><td class="n">${p(e.amount)}</td></tr>`).join("");return`<div class="stub"><div class="stub-head"><div><div class="stub-co">Converted statement</div><div class="stub-addr">${c.length} transactions \xB7 ${C().length} months</div></div><div class="stub-meta"><button type="button" class="btn" id="bank-csv">Download CSV (opens in Excel)</button></div></div>
<table class="stub-t"><thead><tr><th>Date</th><th>Description</th><th class="n">Amount</th></tr></thead><tbody>${t}${c.length>15?`<tr><td colspan="3" class="muted">\u2026 ${c.length-15} more rows in the download</td></tr>`:""}</tbody></table></div>`}function Z(){const t=[["date","description","amount","type"]].concat(c.map(s=>[I(s.date),'"'+s.desc.replace(/"/g,'""')+'"',s.amount.toFixed(2),s.amount<0?"debit":"credit"])),e=new Blob([t.map(s=>s.join(",")).join(`
`)],{type:"text/csv"}),n=document.createElement("a");n.href=URL.createObjectURL(e),n.download="statement.csv",n.click()}const P=u("#bank-form"),K=()=>{const t={};return new FormData(P).forEach((e,n)=>t[n]=e),t.includeTransfers=!!t.includeTransfers,t.business=t.accountType==="business",t};let S={valid:!1};const E="ps_key_proof";function k(){const t=K(),e=u("#bank-out");if(T==="income"){e.innerHTML=_(t);const s=u("#proof");if(s){s.innerHTML=q(t,S.valid);const o=u("#doc-download");o&&(o.disabled=!S.valid)}}else if(T==="recurring")e.innerHTML=B();else if(T==="convert"){e.innerHTML=W();const s=u("#bank-csv");s&&s.addEventListener("click",Z)}const n=u("#bank-cta");n&&(n.hidden=!c.length)}async function j(t,e){if(t){try{const s=await(await fetch("https://paysums.com/api/v1/license?product=proof&key="+encodeURIComponent(t)+(e?"&use=1":""))).json();S={valid:!!s.valid};const o=u("#doc-status");o&&(o.textContent=s.valid?`Licensed \u2014 ${s.max?s.max-(s.uses||0)+" of "+s.max+" downloads left":"download enabled"}.`:s.error||"Key not valid.");try{s.valid?localStorage.setItem(E,t):localStorage.removeItem(E)}catch(a){}}catch(n){S={valid:!1}}k()}}u("#bank-files").addEventListener("change",t=>D([...t.target.files],u("#bank-paste").value)),u("#bank-go").addEventListener("click",()=>D([...u("#bank-files").files],u("#bank-paste").value)),P.addEventListener("change",k),P.addEventListener("input",t=>{t.target.id!=="bank-paste"&&k()});const x=u("#doc-key-btn");x&&x.addEventListener("click",()=>j(u("#doc-key").value.trim(),!1));const H=u("#doc-download");H&&H.addEventListener("click",async()=>{const t=u("#doc-key").value.trim()||(function(){try{return localStorage.getItem(E)||""}catch(e){return""}})();await j(t,!0),S.valid&&(document.body.classList.add("print-proof"),window.print(),setTimeout(()=>document.body.classList.remove("print-proof"),1e3))});try{const t=localStorage.getItem(E);t&&(u("#doc-key")&&(u("#doc-key").value=t),j(t,!1))}catch(t){}u("#bank-demo")&&u("#bank-demo").addEventListener("click",()=>{u("#bank-paste").value=z,D([],z)});const z=`date,description,amount
2026-03-03,ACME CONSULTING LLC ACH PAYROLL,4250.00
2026-03-05,NETFLIX.COM,-15.49
2026-03-07,UBER EATS,-32.10
2026-03-10,SPOTIFY USA,-11.99
2026-03-15,STRIPE TRANSFER ST-XY12,2140.55
2026-03-18,ZELLE FROM SELF SAVINGS,1000.00
2026-03-20,GEICO INSURANCE,-142.00
2026-03-28,RENT PAYMENT ACH,-1850.00
2026-04-03,ACME CONSULTING LLC ACH PAYROLL,4250.00
2026-04-05,NETFLIX.COM,-15.49
2026-04-10,SPOTIFY USA,-11.99
2026-04-14,STRIPE TRANSFER ST-XY19,1980.20
2026-04-20,GEICO INSURANCE,-142.00
2026-04-28,RENT PAYMENT ACH,-1850.00
2026-05-03,ACME CONSULTING LLC ACH PAYROLL,4250.00
2026-05-05,NETFLIX.COM,-17.99
2026-05-10,SPOTIFY USA,-11.99
2026-05-16,STRIPE TRANSFER ST-XY31,2310.00
2026-05-20,GEICO INSURANCE,-142.00
2026-05-22,ADOBE CREATIVE CLOUD,-59.99
2026-05-28,RENT PAYMENT ACH,-1850.00`;k()})();
