/* paysums payroll ledger — DIY payroll for household and micro employers, entirely in the browser (localStorage).
   Each pay run: withholding from the engine (tax.js), employer taxes at statutory rates, a stub; the ledger keeps
   YTD totals, the quarter tab produces Form 941 / Schedule H figures, the year-end tab the W-2 copies.
   Free: one employee, watermarked stubs. Subscription key (product=payroll) unlocks everything. No filing, no money
   movement — the employer deposits and files; this keeps the numbers and the paper right. */
(function () {
  'use strict';
  const root = document.getElementById('pr-app'); if (!root) return;
  const $ = (s, r) => (r || root).querySelector(s); const PD = window.PS_D || {}; const D = PD.us; const F = D.federal; const PC = window.PC; const R = (window.PS_DOCS || {}).R || {}; const H = (window.PS_DOCS || {}).H || {};
  const esc = s => String(s == null ? '' : s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  const fmt = x => '$' + (Math.round((+x || 0) * 100) / 100).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const fdate = s => { if (!s) return '—'; const d = new Date(s + 'T00:00:00'); return isNaN(d) ? esc(s) : d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }); };
  const PER = { weekly: 52, biweekly: 26, semimonthly: 24, monthly: 12 }; const KEY = 'ps_payroll', LK = 'ps_key_payroll';
  const uid = () => Math.random().toString(36).slice(2, 9);
  let S = { employer: { kind: 'household', state: 'TX', sutaRate: 2.7, sutaBase: 7000 }, employees: [], runs: [] };
  try { const s = JSON.parse(localStorage.getItem(KEY) || 'null'); if (s && s.employees) S = Object.assign(S, s); } catch (e) {}
  const save = () => { try { localStorage.setItem(KEY, JSON.stringify(S)); } catch (e) {} };
  let lic = { valid: false, checked: 0 }; try { lic = JSON.parse(localStorage.getItem(LK + '_lic') || '{"valid":false}'); } catch (e) {}
  const paid = () => !!lic.valid;
  let tab = location.hash.replace('#', '') || 'setup'; const TABS = [['setup', 'Employer'], ['employees', 'Employees'], ['run', 'Run payroll'], ['ledger', 'Ledger'], ['quarter', 'Quarter'], ['yearend', 'Year-end'], ['backup', 'Backup & key']];
  const year = () => +($('#pr-year') ? $('#pr-year').value : 0) || new Date().getFullYear();
  const runsOf = (empId, y, before, excludeId) => S.runs.filter(r => r.empId === empId && r.payDate.slice(0, 4) === String(y) && (!before || r.payDate <= before) && r.id !== excludeId).sort((a, b) => a.payDate.localeCompare(b.payDate));
  const sum = (rs, f) => rs.reduce((a, r) => a + f(r), 0);
  const stateName = c => (D.states[c] || {}).name || c;

  /* ---------- a pay run ---------- */
  function compute(e, inp) {
    const n = PER[e.frequency] || 26; const hourly = e.payType === 'hourly';
    const hours = +inp.hours || 0, ot = +inp.ot || 0, rate = +e.rate || 0; const gross = hourly ? rate * hours + rate * 1.5 * ot : (+inp.gross || +e.rate || 0);
    const r = PC.calc('US', { amount: gross, period: e.frequency, state: e.state || S.employer.state, filing: e.filing || 'single', k401Pct: +e.k401Pct || 0, health: (+e.health || 0) * n, local: e.local || '', dependents: +e.dependents || 0, extraWithholding: +e.extra || 0, twoJobs: e.twoJobs === 'yes', otherIncome: +e.otherIncome || 0 }, D);
    const items = r.items.filter(i => i.amount / n > 0.004).map(i => ({ key: i.key, label: i.label, amount: Math.round(i.amount / n * 100) / 100, kind: i.kind }));
    // Social Security wage base and FUTA/SUTA bases on actual YTD, not the annualized estimate
    const prev = runsOf(e.id, inp.payDate.slice(0, 4), inp.payDate, inp.id); const ytdGross = sum(prev, x => x.gross), ytdFica = sum(prev, x => x.ficaWages || x.gross);
    const ficaWages = Math.max(0, gross - (+e.health || 0)); const ssRoom = Math.max(0, F.ss.wageBase - ytdFica); const ssW = Math.min(ficaWages, ssRoom);
    const ssI = items.find(i => i.key === 'ss'); if (ssI) ssI.amount = Math.round(ssW * F.ss.rate * 100) / 100; else if (ssW > 0) items.push({ key: 'ss', label: 'Social Security', amount: Math.round(ssW * F.ss.rate * 100) / 100, kind: 'tax' });
    const medI = items.find(i => i.key === 'medicare'); const addl = Math.max(0, Math.min(ficaWages, ytdFica + ficaWages - F.medicare.addlThreshold)); if (medI) medI.amount = Math.round((ficaWages * F.medicare.rate + addl * F.medicare.addlRate) * 100) / 100;
    const ded = sum(items, i => i.amount); const net = Math.round((gross - ded) * 100) / 100;
    const futaW = Math.max(0, Math.min(gross, F.futa.base - ytdGross)), sutaW = Math.max(0, Math.min(gross, (+S.employer.sutaBase || 7000) - ytdGross));
    const er = { ss: Math.round(ssW * F.ss.rate * 100) / 100, med: Math.round(ficaWages * F.medicare.rate * 100) / 100, futa: Math.round(futaW * F.futa.rate * 100) / 100, suta: Math.round(sutaW * ((+S.employer.sutaRate || 0) / 100) * 100) / 100 };
    return { gross, hours, ot, rate, items, net, er, ficaWages, ssWages: ssW, fit: (items.find(i => i.key === 'federal') || {}).amount || 0, stateTax: (items.find(i => i.key === 'state') || {}).amount || 0, localTax: (items.find(i => i.key === 'local') || {}).amount || 0, k401: (items.find(i => i.key === 'k401') || {}).amount || 0, health: (items.find(i => i.key === 'health') || {}).amount || 0 };
  }
  function stubHtml(e, run) {
    const y = run.payDate.slice(0, 4); const ytdRuns = runsOf(e.id, y, run.payDate, run.id).concat([run]); const ytd = f => fmt(sum(ytdRuns, f)); const n = PER[e.frequency] || 26; const k = ytdRuns.length;
    const earn = e.payType === 'hourly' ? `<tr><td>Regular (${(+run.hours).toFixed(2)} h × ${fmt(run.rate)})</td><td class="n">${fmt(run.rate * run.hours)}</td><td class="n">${ytd(r => r.rate * r.hours)}</td></tr>` + (run.ot > 0 ? `<tr><td>Overtime (${(+run.ot).toFixed(2)} h × ${fmt(run.rate * 1.5)})</td><td class="n">${fmt(run.rate * 1.5 * run.ot)}</td><td class="n">${ytd(r => r.rate * 1.5 * (r.ot || 0))}</td></tr>` : '') : `<tr><td>Salary</td><td class="n">${fmt(run.gross)}</td><td class="n">${ytd(r => r.gross)}</td></tr>`;
    const line = key => ytd(r => (r.items.find(i => i.key === key) || {}).amount || 0);
    return `<div class="stub${paid() ? '' : ' wm'}"><div class="stub-head"><div><div class="stub-co">${esc(S.employer.name) || 'Employer'}</div><div class="stub-addr">${esc(S.employer.addr || '').replace(/\n/g, '<br>')}${S.employer.ein ? '<br>EIN ' + esc(S.employer.ein) : ''}</div></div><div class="stub-meta"><div><b>Earnings statement</b></div><div>Pay period: ${fdate(run.periodStart)} – ${fdate(run.periodEnd)}</div><div>Pay date: ${fdate(run.payDate)}</div><div>Check no. ${k} of ${y} (${esc(e.frequency)})</div></div></div>
<div class="stub-emp"><div><b>${esc(e.name)}</b><br>${esc(e.addr || '').replace(/\n/g, '<br>')}</div><div>${e.ssn ? 'SSN ***-**-' + esc(String(e.ssn).replace(/[^0-9]/g, '').slice(-4)) + '<br>' : ''}${({ married: 'Married filing jointly', head: 'Head of household' }[e.filing] || 'Single')} · ${esc(stateName(e.state || S.employer.state))}</div></div>
<table class="stub-t"><thead><tr><th>Earnings</th><th class="n">This period</th><th class="n">Year to date</th></tr></thead><tbody>${earn}<tr class="tot"><td>Gross pay</td><td class="n">${fmt(run.gross)}</td><td class="n">${ytd(r => r.gross)}</td></tr></tbody></table>
<table class="stub-t"><thead><tr><th>Taxes and deductions</th><th class="n">This period</th><th class="n">Year to date</th></tr></thead><tbody>${run.items.map(i => `<tr><td>${esc(i.label)}</td><td class="n">${fmt(i.amount)}</td><td class="n">${line(i.key)}</td></tr>`).join('')}<tr class="tot"><td>Total deductions</td><td class="n">${fmt(run.gross - run.net)}</td><td class="n">${ytd(r => r.gross - r.net)}</td></tr></tbody></table>
<div class="stub-net"><span>Net pay</span><b>${fmt(run.net)}</b><span class="ytd">YTD ${ytd(r => r.net)}</span></div>
<p class="stub-foot">Employer payroll record: prepared by ${esc(S.employer.name) || 'the employer'} with paysums.com payroll on ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}. Federal, state and local withholding computed from the ${esc(D.year)} tables and the employee's W-4 elections; FICA at statutory rates${S.employer.kind === 'household' ? '; household employment (Schedule H)' : ''}.</p>${paid() ? '' : '<div class="stub-mark">PREVIEW</div>'}</div>`;
  }

  /* ---------- views ---------- */
  const inp = (label, name, val, type, extra) => `<div class="field"><span>${label}</span><input type="${type || 'text'}" name="${name}" value="${esc(val == null ? '' : val)}" ${extra || ''}></div>`;
  const sel = (label, name, opts, cur) => `<div class="field"><span>${label}</span><select name="${name}">${opts.map(([v, t]) => `<option value="${v}"${String(v) === String(cur) ? ' selected' : ''}>${esc(t)}</option>`).join('')}</select></div>`;
  const stateOpts = Object.keys(D.states).sort((a, b) => D.states[a].name.localeCompare(D.states[b].name)).map(c => [c, D.states[c].name]);
  const empOpts = () => S.employees.map(e => [e.id, e.name || '(unnamed)']);
  const V = {};
  V.setup = () => { const E = S.employer; return `<form id="f-emp" class="f stub-form"><fieldset><legend>Employer</legend>${sel('Type of employer', 'kind', [['household', 'Household (nanny, caregiver, housekeeper) — Schedule H'], ['business', 'Business — Form 941/944']], E.kind)}${inp('Name on stubs and forms', 'name', E.name, 'text', 'maxlength="80" required')}${inp('EIN', 'ein', E.ein, 'text', 'maxlength="11" placeholder="12-3456789"')}<div class="field"><span>Address</span><textarea name="addr" rows="2" maxlength="200">${esc(E.addr || '')}</textarea></div>${sel('Work state (default for employees)', 'state', stateOpts, E.state)}<div class="row2">${inp('State unemployment (SUTA) rate %', 'sutaRate', E.sutaRate, 'number', 'min="0" max="15" step="0.01"')}${inp('SUTA wage base', 'sutaBase', E.sutaBase, 'number', 'min="0" step="100"')}</div><p class="muted small">Your SUTA rate is on the state's annual rate notice; new employers get a standard rate. FUTA is fixed at ${(F.futa.rate * 100).toFixed(1)}% of the first ${fmt(F.futa.base)}.</p><button class="btn" type="submit">Save employer</button></fieldset></form>`; };
  V.employees = () => { const list = S.employees.map(e => `<tr><td><b>${esc(e.name)}</b><br><span class="small muted">${e.payType === 'hourly' ? fmt(e.rate) + '/h' : fmt(e.rate) + ' per ' + e.frequency.replace('biweekly', 'two weeks').replace('semimonthly', 'half-month')} · ${esc(stateName(e.state || S.employer.state))} · ${esc(e.filing)}</span></td><td><button class="btn sm ghost" data-edit="${e.id}">Edit</button> <button class="btn sm ghost" data-del="${e.id}">Remove</button></td></tr>`).join('');
    const e = V._edit || { id: '', frequency: 'biweekly', payType: 'hourly', filing: 'single', state: S.employer.state, k401Pct: 0, health: 0, dependents: 0, extra: 0 };
    const locals = ((D.states[e.state || S.employer.state] || {}).locals || []);
    return `<table class="stub-t"><tbody>${list || '<tr><td>No employees yet.</td></tr>'}</tbody></table>${!paid() && S.employees.length >= 1 && !V._edit ? '<p class="muted small">Free plan: one employee. Add a subscription key (Backup &amp; key tab) for unlimited employees and clean stubs.</p>' : ''}
<form id="f-e" class="f stub-form"><input type="hidden" name="eid" value="${esc(e.id)}"><fieldset><legend>${e.id ? 'Edit' : 'Add'} employee</legend>${inp('Name', 'name', e.name, 'text', 'maxlength="80" required')}<div class="field"><span>Address</span><textarea name="addr" rows="2" maxlength="200">${esc(e.addr || '')}</textarea></div><div class="row2">${inp('SSN (stored only in this browser; masked on stubs)', 'ssn', e.ssn, 'text', 'maxlength="11" inputmode="numeric"')}${inp('Start date', 'start', e.start, 'date')}</div>
<div class="row3">${sel('Pay type', 'payType', [['hourly', 'Hourly'], ['salary', 'Salary per period']], e.payType)}${inp('Rate (per hour, or per pay period)', 'rate', e.rate, 'number', 'min="0" step="0.01" required')}${sel('Pay frequency', 'frequency', [['weekly', 'Weekly'], ['biweekly', 'Bi-weekly'], ['semimonthly', 'Semi-monthly'], ['monthly', 'Monthly']], e.frequency)}</div>
<div class="row2">${sel('Work state', 'state', stateOpts, e.state || S.employer.state)}<div class="field"><span>City / local tax</span><select name="local"><option value="">None</option>${locals.map(l => `<option value="${l.key}"${l.key === e.local ? ' selected' : ''}>${esc(l.name)}</option>`).join('')}</select></div></div>
<legend class="sub">From the employee's W-4</legend><div class="row2">${sel('Step 1(c) filing status', 'filing', [['single', 'Single or married filing separately'], ['married', 'Married filing jointly'], ['head', 'Head of household']], e.filing)}${sel('Step 2(c) box checked?', 'twoJobs', [['no', 'No'], ['yes', 'Yes']], e.twoJobs)}</div><div class="row3">${inp('Step 3 credits ($ per year)', 'dependents', e.dependents, 'number', 'min="0" step="1"')}${inp('Step 4(a) other income', 'otherIncome', e.otherIncome, 'number', 'min="0" step="1"')}${inp('Step 4(c) extra per paycheck', 'extra', e.extra, 'number', 'min="0" step="1"')}</div>
<div class="row2">${inp('401(k) % of pay', 'k401Pct', e.k401Pct, 'number', 'min="0" max="100" step="0.5"')}${inp('Health premium per period (pre-tax)', 'health', e.health, 'number', 'min="0" step="0.01"')}</div>
<button class="btn" type="submit">${e.id ? 'Save' : 'Add employee'}</button> ${e.id ? '<button class="btn ghost" type="button" id="e-cancel">Cancel</button>' : ''}</fieldset></form>`; };
  V.run = () => { if (!S.employees.length) return '<p>Add an employee first.</p>'; const e = S.employees.find(x => x.id === V._runEmp) || S.employees[0]; const today = new Date().toISOString().slice(0, 10);
    return `<form id="f-run" class="f stub-form"><fieldset><legend>Pay run</legend>${sel('Employee', 'empId', empOpts(), e.id)}<div class="row3">${inp('Period start', 'periodStart', V._ps || '', 'date', 'required')}${inp('Period end', 'periodEnd', V._pe || '', 'date', 'required')}${inp('Pay date', 'payDate', V._pd || today, 'date', 'required')}</div>${e.payType === 'hourly' ? `<div class="row2">${inp('Regular hours', 'hours', V._hours == null ? (PER[e.frequency] === 52 ? 40 : PER[e.frequency] === 26 ? 80 : 86.67) : V._hours, 'number', 'min="0" step="0.01"')}${inp('Overtime hours (×1.5)', 'ot', V._ot || 0, 'number', 'min="0" step="0.01"')}</div>` : inp('Gross pay this period', 'gross', V._gross == null ? e.rate : V._gross, 'number', 'min="0" step="0.01"')}<button class="btn" type="submit">Preview this pay run</button></fieldset></form><div id="run-preview">${V._previewHtml || ''}</div>`; };
  V.ledger = () => { const y = year(); const rs = S.runs.filter(r => r.payDate.slice(0, 4) === String(y)).sort((a, b) => b.payDate.localeCompare(a.payDate));
    return `${yearSel()}<table class="stub-t ledger"><thead><tr><th>Pay date</th><th>Employee</th><th class="n">Gross</th><th class="n">Fed. WH</th><th class="n">SS+Med (ee)</th><th class="n">State</th><th class="n">Net</th><th class="n">Employer taxes</th><th></th></tr></thead><tbody>${rs.map(r => { const e = S.employees.find(x => x.id === r.empId) || {}; return `<tr><td>${fdate(r.payDate)}</td><td>${esc(e.name)}</td><td class="n">${fmt(r.gross)}</td><td class="n">${fmt(r.fit)}</td><td class="n">${fmt((r.items.find(i => i.key === 'ss') || {}).amount || 0) + ' + ' + fmt((r.items.find(i => i.key === 'medicare') || {}).amount || 0)}</td><td class="n">${fmt(r.stateTax + r.localTax)}</td><td class="n"><b>${fmt(r.net)}</b></td><td class="n">${fmt(r.er.ss + r.er.med + r.er.futa + r.er.suta)}</td><td><button class="btn sm ghost" data-stub="${r.id}">Stub</button> <button class="btn sm ghost" data-check="${r.id}">Check</button> <button class="btn sm ghost" data-rm="${r.id}">×</button></td></tr>`; }).join('') || '<tr><td colspan="9">No pay runs in ' + y + '.</td></tr>'}</tbody>${rs.length ? `<tfoot><tr class="tot"><td colspan="2">Total ${y}</td><td class="n">${fmt(sum(rs, r => r.gross))}</td><td class="n">${fmt(sum(rs, r => r.fit))}</td><td class="n">${fmt(sum(rs, r => ((r.items.find(i => i.key === 'ss') || {}).amount || 0) + ((r.items.find(i => i.key === 'medicare') || {}).amount || 0)))}</td><td class="n">${fmt(sum(rs, r => r.stateTax + r.localTax))}</td><td class="n">${fmt(sum(rs, r => r.net))}</td><td class="n">${fmt(sum(rs, r => r.er.ss + r.er.med + r.er.futa + r.er.suta))}</td><td></td></tr></tfoot>` : ''}</table><div id="stub-out"></div>`; };
  const yearSel = () => { const ys = [...new Set(S.runs.map(r => r.payDate.slice(0, 4)).concat([String(new Date().getFullYear())]))].sort().reverse(); return `<p class="field inline"><span>Year</span> <select id="pr-year">${ys.map(y => `<option${+y === (V._year || +ys[0]) ? ' selected' : ''}>${y}</option>`).join('')}</select></p>`; };
  V.quarter = () => { const y = year(); const q = V._q || Math.ceil((new Date().getMonth() + 1) / 3); const inQ = r => r.payDate.slice(0, 4) === String(y) && Math.ceil((+r.payDate.slice(5, 7)) / 3) === q; const rs = S.runs.filter(inQ);
    const W = sum(rs, r => r.gross), fit = sum(rs, r => r.fit), ssW = sum(rs, r => r.ssWages), mW = sum(rs, r => r.ficaWages), add = sum(rs, r => Math.max(0, 0)); const l5a = ssW * 0.124, l5c = mW * 0.029, tot = fit + l5a + l5c;
    const months = [0, 1, 2].map(i => sum(rs.filter(r => (+r.payDate.slice(5, 7) - 1) % 3 === i), r => r.fit + ((r.items.find(x => x.key === 'ss') || {}).amount || 0) * 2 + ((r.items.find(x => x.key === 'medicare') || {}).amount || 0) * 2));
    const hh = S.employer.kind === 'household'; const empCount = new Set(rs.map(r => r.empId)).size;
    const q941 = `/form-941-calculator/?name=${encodeURIComponent(S.employer.name || '')}&ein=${encodeURIComponent(S.employer.ein || '')}&quarter=${q}&year=${y}&employees=${empCount}&wages=${W.toFixed(2)}&fit=${fit.toFixed(2)}&ssWages=${ssW.toFixed(2)}&medWages=${mW.toFixed(2)}&m1=${months[0].toFixed(2)}&m2=${months[1].toFixed(2)}&m3=${months[2].toFixed(2)}`;
    return `${yearSel()}<p class="field inline"><span>Quarter</span> <select id="pr-q">${[1, 2, 3, 4].map(i => `<option value="${i}"${i === q ? ' selected' : ''}>Q${i}</option>`).join('')}</select></p>
<table class="stub-t"><tbody><tr><td>Wages paid (${rs.length} pay run${rs.length === 1 ? '' : 's'}, ${empCount} employee${empCount === 1 ? '' : 's'})</td><td class="n">${fmt(W)}</td></tr><tr><td>Federal income tax withheld</td><td class="n">${fmt(fit)}</td></tr><tr><td>Social Security wages ${fmt(ssW)} × 12.4% (both shares)</td><td class="n">${fmt(l5a)}</td></tr><tr><td>Medicare wages ${fmt(mW)} × 2.9% (both shares)</td><td class="n">${fmt(l5c)}</td></tr><tr class="tot"><td>Total federal employment tax for the quarter</td><td class="n">${fmt(tot)}</td></tr><tr><td>Employer FUTA accrued</td><td class="n">${fmt(sum(rs, r => r.er.futa))}</td></tr><tr><td>Employer SUTA accrued (${S.employer.sutaRate}%)</td><td class="n">${fmt(sum(rs, r => r.er.suta))}</td></tr><tr><td>State income tax withheld (remit to the state)</td><td class="n">${fmt(sum(rs, r => r.stateTax + r.localTax))}</td></tr></tbody></table>
${hh ? `<p><b>Household employer.</b> These amounts go on <a href="/schedule-h-calculator/">Schedule H</a> with your ${y} Form 1040 (due April 15, ${y + 1}); no quarterly 941. Cover them during the year by raising your own W-4 withholding or paying estimated tax — ${fmt(tot / 3)} a month would cover this quarter's pace.</p>` : `<p><b>Form 941 for Q${q}</b> is due ${['April 30', 'July 31', 'October 31', 'January 31'][q - 1]}. ${tot < 2500 ? 'Under $2,500 for the quarter: you may pay with the return.' : 'Monthly depositor: deposit each month\'s liability by the 15th of the next month through EFTPS — month 1 ' + fmt(months[0]) + ', month 2 ' + fmt(months[1]) + ', month 3 ' + fmt(months[2]) + '.'} <a class="btn sm" href="${q941}" target="_blank" rel="noopener">Open the filled 941 worksheet</a></p>`}
<p><button class="btn sm ghost" id="ics">Download deadline reminders (.ics)</button> <span class="muted small">deposit dates, 941/Schedule H, W-2 — adds to Google/Apple/Outlook calendar</span></p>`; };
  V.yearend = () => { const y = year(); const emps = S.employees.filter(e => runsOf(e.id, y).length); if (!emps.length) return yearSel() + '<p>No pay runs in ' + y + '.</p>';
    const v = { taxYear: y, pname: S.employer.name, pein: S.employer.ein, paddr: S.employer.addr, state: S.employer.state, stateId: S.employer.stateId || '' }; ['ename', 'etin', 'eaddr', 'egross', 'ek401', 'ehealth', 'ehsa', 'efed', 'estate', 'elocal'].forEach(k => v[k + '[]'] = []);
    const rows = emps.map(e => { const rs = runsOf(e.id, y); const g = sum(rs, r => r.gross); v['ename[]'].push(e.name); v['etin[]'].push(e.ssn || ''); v['eaddr[]'].push(e.addr || ''); v['egross[]'].push(g); v['ek401[]'].push(sum(rs, r => r.k401)); v['ehealth[]'].push(sum(rs, r => r.health)); v['ehsa[]'].push(0); v['efed[]'].push(sum(rs, r => r.fit)); v['estate[]'].push(sum(rs, r => r.stateTax)); v['elocal[]'].push(sum(rs, r => r.localTax));
      return `<tr><td>${esc(e.name)}</td><td class="n">${fmt(g)}</td><td class="n">${fmt(sum(rs, r => r.fit))}</td><td class="n">${fmt(sum(rs, r => r.ssWages))}</td><td class="n">${fmt(sum(rs, r => r.stateTax))}</td><td class="n">${fmt(sum(rs, r => r.net))}</td></tr>`; }).join('');
    const w2 = R.w2form ? R.w2form(v) : '<p>W-2 renderer not loaded.</p>';
    const thr = F.householdThreshold || 3000; const under = S.employer.kind === 'household' ? emps.filter(e => sum(runsOf(e.id, y), r => r.gross) < thr) : [];
    return `${yearSel()}<table class="stub-t"><thead><tr><th>Employee</th><th class="n">Gross</th><th class="n">Federal WH</th><th class="n">SS wages</th><th class="n">State WH</th><th class="n">Net paid</th></tr></thead><tbody>${rows}</tbody></table>
${under.length ? `<p class="muted small">Household threshold: ${under.map(e => esc(e.name)).join(', ')} earned under ${fmt(thr)} in ${y}, so no Social Security or Medicare is due on those wages — refund any withheld and leave boxes 3–6 blank (edit before filing).</p>` : ''}
<p>W-2 copies (Copy B/C) and W-3 totals below — print for employees by January 31 and file Copy A free through SSA Business Services Online. ${paid() ? '' : '<b>Subscription required to print clean copies.</b>'}</p><div class="${paid() ? '' : 'wm-wrap'}">${w2}</div>${paid() ? '<p><button class="btn" id="print-w2">Print W-2s</button></p>' : ''}`; };
  V.backup = () => `<h3>Subscription key</h3><p class="muted small">Free plan: one employee, watermarked stubs. The subscription (${esc(root.dataset.price || '$12 a month')}) unlocks unlimited employees, clean stubs and checks, W-2 printing. Keys are checked against the licence server once a week.</p><div class="stub-actions"><input type="text" id="pr-key" placeholder="Paste your subscription key" value="${esc((function () { try { return localStorage.getItem(LK) || ''; } catch (e) { return ''; } })())}"><button class="btn sm" id="pr-key-btn">Apply key</button></div><p id="pr-key-status" class="muted small">${paid() ? 'Subscription active.' : 'No active subscription.'}</p>${root.dataset.buy ? `<p><a class="btn" href="${esc(root.dataset.buy)}" rel="noopener">Subscribe — ${esc(root.dataset.price || '')}</a></p>` : `<p><a class="btn" href="/contact/?re=payroll">Request a subscription key — ${esc(root.dataset.price || '')}</a> <span class="muted small">(checkout opening shortly)</span></p>`}
<h3>Backup</h3><p class="muted small">Everything lives in this browser only. Download a backup after each pay run and keep it with your payroll records (four years).</p><p><button class="btn sm" id="bk-out">Download backup (JSON)</button> <label class="btn sm ghost">Restore backup <input type="file" id="bk-in" accept="application/json" hidden></label> <button class="btn sm ghost" id="bk-clear">Erase all payroll data</button></p>`;

  /* ---------- render + events ---------- */
  function render() { root.innerHTML = `<nav class="pr-tabs">${TABS.map(([k, t]) => `<a href="#${k}" class="${k === tab ? 'cur' : ''}">${t}</a>`).join('')}</nav><div class="pr-body">${V[tab]()}</div>`; }
  root.addEventListener('click', e => { const a = e.target.closest('.pr-tabs a'); if (a) { tab = a.getAttribute('href').slice(1); V._edit = null; render(); } });
  root.addEventListener('submit', e => { e.preventDefault(); const f = e.target; const fid = f.getAttribute('id'); const v = Object.fromEntries(new FormData(f).entries());
    if (fid === 'f-emp') { Object.assign(S.employer, v); save(); tab = 'employees'; render(); }
    if (fid === 'f-e') { const id = v.eid; delete v.eid; if (!id && !paid() && S.employees.length >= 1) { alert('The free plan covers one employee. Add a subscription key for more.'); return; } if (id) { const i = S.employees.findIndex(x => x.id === id); S.employees[i] = Object.assign(S.employees[i], v); } else { v.id = uid(); S.employees.push(v); } V._edit = null; save(); render(); }
    if (fid === 'f-run') { const emp = S.employees.find(x => x.id === v.empId); V._runEmp = emp.id; V._ps = v.periodStart; V._pe = v.periodEnd; V._pd = v.payDate; V._hours = v.hours; V._ot = v.ot; V._gross = v.gross; const c = compute(emp, v); const run = Object.assign({ id: uid(), empId: emp.id, periodStart: v.periodStart, periodEnd: v.periodEnd, payDate: v.payDate }, c); V._pending = run;
      V._previewHtml = `<table class="stub-t"><tbody><tr><td>Gross</td><td class="n">${fmt(run.gross)}</td></tr>${run.items.map(i => `<tr><td>${esc(i.label)}</td><td class="n">−${fmt(i.amount)}</td></tr>`).join('')}<tr class="tot"><td>Net pay to ${esc(emp.name)}</td><td class="n"><b>${fmt(run.net)}</b></td></tr><tr><td>Employer taxes: SS ${fmt(run.er.ss)} · Medicare ${fmt(run.er.med)} · FUTA ${fmt(run.er.futa)} · SUTA ${fmt(run.er.suta)}</td><td class="n">${fmt(run.er.ss + run.er.med + run.er.futa + run.er.suta)}</td></tr><tr><td>Total cost of this pay run</td><td class="n">${fmt(run.gross + run.er.ss + run.er.med + run.er.futa + run.er.suta)}</td></tr></tbody></table><p><button class="btn" id="run-save">Record this pay run</button> <span class="muted small">then print the stub from the Ledger tab</span></p>`; $('#run-preview').innerHTML = V._previewHtml; }
  });
  root.addEventListener('change', e => { if (e.target.id === 'pr-year') { V._year = +e.target.value; render(); } if (e.target.id === 'pr-q') { V._q = +e.target.value; render(); } if (e.target.name === 'empId' && tab === 'run') { V._runEmp = e.target.value; render(); } if (e.target.name === 'state' && tab === 'employees') { const loc = $('select[name=local]'); if (loc) { const ls = (D.states[e.target.value] || {}).locals || []; loc.innerHTML = '<option value="">None</option>' + ls.map(l => `<option value="${l.key}">${esc(l.name)}</option>`).join(''); } } if (e.target.id === 'bk-in') { const fr = new FileReader(); fr.onload = () => { try { const s = JSON.parse(fr.result); if (s.employees && s.runs) { S = s; save(); render(); } } catch (x) { alert('Not a paysums payroll backup.'); } }; fr.readAsText(e.target.files[0]); } });
  root.addEventListener('click', async e => { const t = e.target;
    if (t.dataset.edit) { V._edit = S.employees.find(x => x.id === t.dataset.edit); render(); }
    if (t.id === 'e-cancel') { V._edit = null; render(); }
    if (t.dataset.del && confirm('Remove this employee? Their pay runs stay in the ledger.')) { S.employees = S.employees.filter(x => x.id !== t.dataset.del); save(); render(); }
    if (t.id === 'run-save' && V._pending) { S.runs.push(V._pending); save(); V._pending = null; V._previewHtml = ''; V._ps = V._pe = V._pd = null; tab = 'ledger'; location.hash = 'ledger'; render(); }
    if (t.dataset.rm && confirm('Delete this pay run?')) { S.runs = S.runs.filter(r => r.id !== t.dataset.rm); save(); render(); }
    if (t.dataset.stub) { const r = S.runs.find(x => x.id === t.dataset.stub); const emp = S.employees.find(x => x.id === r.empId); $('#stub-out').innerHTML = stubHtml(emp, r) + (paid() ? '<p><button class="btn" id="print-stub">Print / save PDF</button></p>' : '<p class="muted small">Subscription required to print clean stubs.</p>'); $('#stub-out').scrollIntoView({ behavior: 'smooth' }); }
    if (t.dataset.check) { const r = S.runs.find(x => x.id === t.dataset.check); const emp = S.employees.find(x => x.id === r.empId); location.href = `/check-printer/?payer=${encodeURIComponent(S.employer.name || '')}&payerAddr=${encodeURIComponent(S.employer.addr || '')}&date=${r.payDate}&payee[]=${encodeURIComponent(emp.name)}&amount[]=${r.net.toFixed(2)}&memo[]=${encodeURIComponent('Pay period ' + r.periodStart + ' to ' + r.periodEnd)}`; }
    if (t.id === 'print-stub' || t.id === 'print-w2') { root.classList.add('printing'); window.print(); root.classList.remove('printing'); }
    if (t.id === 'ics') { const y = year(); const ev = []; const add = (d, s) => ev.push(`BEGIN:VEVENT\r\nDTSTART;VALUE=DATE:${d.replace(/-/g, '')}\r\nSUMMARY:${s}\r\nEND:VEVENT`);
      if (S.employer.kind === 'household') { add(`${y + 1}-01-31`, 'Give W-2s to household employees; file Copy A with SSA'); add(`${y + 1}-04-15`, 'Schedule H with Form 1040 — household employment taxes'); [4, 6, 9].forEach(m => add(`${y}-0${m}-15`, 'Estimated tax payment (covers nanny taxes)')); add(`${y + 1}-01-15`, 'Estimated tax payment (covers nanny taxes)'); }
      else { for (let m = 1; m <= 12; m++) add(`${m === 12 ? y + 1 : y}-${String(m === 12 ? 1 : m + 1).padStart(2, '0')}-15`, 'EFTPS deposit — payroll taxes for ' + new Date(y, m - 1, 1).toLocaleString('en-US', { month: 'long' })); [[4, 30], [7, 31], [10, 31]].forEach(([m, d]) => add(`${y}-${String(m).padStart(2, '0')}-${d}`, 'Form 941 due')); add(`${y + 1}-01-31`, 'Form 941 (Q4), Form 940, W-2s to employees and SSA'); }
      const ics = 'BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//paysums//payroll//EN\r\n' + ev.join('\r\n') + '\r\nEND:VCALENDAR'; const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([ics], { type: 'text/calendar' })); a.download = 'payroll-deadlines-' + y + '.ics'; a.click(); }
    if (t.id === 'bk-out') { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([JSON.stringify(S, null, 1)], { type: 'application/json' })); a.download = 'paysums-payroll-' + new Date().toISOString().slice(0, 10) + '.json'; a.click(); }
    if (t.id === 'bk-clear' && confirm('Erase every employee and pay run from this browser? Download a backup first.')) { S = { employer: { kind: 'household', state: 'TX', sutaRate: 2.7, sutaBase: 7000 }, employees: [], runs: [] }; save(); render(); }
    if (t.id === 'pr-key-btn') { const key = $('#pr-key').value.trim(); const st = $('#pr-key-status'); st.textContent = 'Checking…'; try { const r = await fetch('https://paysums.com/api/v1/license?product=payroll&key=' + encodeURIComponent(key)); const d = await r.json(); lic = { valid: !!d.valid, checked: Date.now() }; localStorage.setItem(LK + '_lic', JSON.stringify(lic)); if (d.valid) localStorage.setItem(LK, key); st.textContent = d.valid ? 'Subscription active — thank you.' : (d.error || 'Key not valid.'); render(); } catch (x) { st.textContent = 'Could not reach the licence server.'; } }
  });
  // weekly re-check of a stored key
  (async function () { try { const key = localStorage.getItem(LK); if (key && (!lic.checked || Date.now() - lic.checked > 7 * 86400e3)) { const r = await fetch('https://paysums.com/api/v1/license?product=payroll&key=' + encodeURIComponent(key)); const d = await r.json(); lic = { valid: !!d.valid, checked: Date.now() }; localStorage.setItem(LK + '_lic', JSON.stringify(lic)); render(); } } catch (e) {} })();
  addEventListener('hashchange', () => { const t = location.hash.replace('#', '') || 'setup'; if (t !== tab) { tab = t; V._edit = null; render(); } });
  render();
})();
